### ISSUE TITLE
TODO 전체 완료

### ISSUE THREAD

**Issue by KingGyeongHoo** [KingGyeongHoo/todo-githubflow#8]
### 만들고자 하는 기능이 무엇인가요?
TODO 전체 완료

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] 모든 TODO 객체들의 isComplete를 true로 변경
2. [ ] 서버로 TODO 객체들을 전달 뒤 저장
3. [ ] 모든 컴포넌트들의 배경색을 Gray로, 글자색을 DARK GRAY로 변경

### 예상 작업 시간
3h
